CONFIG_STD_C23=y
CONFIG_GNU_C_EXTENSIONS=y
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_BUILD_OUTPUT_S19=y

CONFIG_GPIO=y

CONFIG_LOG=y
CONFIG_LOG_RUNTIME_FILTERING=y

CONFIG_BINDESC=y
CONFIG_BINDESC_DEFINE=y
CONFIG_BINDESC_DEFINE_VERSION=y
CONFIG_BINDESC_KERNEL_VERSION_STRING=y
CONFIG_BINDESC_KERNEL_VERSION_MAJOR=y
CONFIG_BINDESC_KERNEL_VERSION_MINOR=y
CONFIG_BINDESC_KERNEL_VERSION_PATCHLEVEL=y
CONFIG_BINDESC_KERNEL_VERSION_NUMBER=y
CONFIG_BINDESC_KERNEL_BUILD_VERSION=y
CONFIG_BINDESC_APP_VERSION_STRING=y
CONFIG_BINDESC_APP_VERSION_MAJOR=y
CONFIG_BINDESC_APP_VERSION_MINOR=y
CONFIG_BINDESC_APP_VERSION_PATCHLEVEL=y
CONFIG_BINDESC_APP_VERSION_NUMBER=y
CONFIG_BINDESC_APP_BUILD_VERSION=y
CONFIG_BINDESC_DEFINE_BUILD_TIME=y
CONFIG_BINDESC_BUILD_TIME_YEAR=y
CONFIG_BINDESC_BUILD_TIME_MONTH=y
CONFIG_BINDESC_BUILD_TIME_DAY=y
CONFIG_BINDESC_BUILD_TIME_HOUR=y
CONFIG_BINDESC_BUILD_TIME_MINUTE=y
CONFIG_BINDESC_BUILD_TIME_SECOND=y
CONFIG_BINDESC_BUILD_TIME_UNIX=y
CONFIG_BINDESC_BUILD_DATE_TIME_STRING=y
CONFIG_BINDESC_BUILD_DATE_STRING=y
CONFIG_BINDESC_BUILD_TIME_STRING=y
CONFIG_BINDESC_DEFINE_HOST_INFO=y
CONFIG_BINDESC_HOST_NAME=y
CONFIG_BINDESC_C_COMPILER_NAME=y
CONFIG_BINDESC_C_COMPILER_VERSION=y
CONFIG_BINDESC_CXX_COMPILER_NAME=y
CONFIG_BINDESC_CXX_COMPILER_VERSION=y
CONFIG_BINDESC_READ=y
CONFIG_BINDESC_READ_RAM=y
CONFIG_BINDESC_READ_MEMORY_MAPPED_FLASH=y
CONFIG_BINDESC_READ_FLASH=y
