# Debug
CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_SPEED_OPTIMIZATIONS is not set
CONFIG_STM32_ENABLE_DEBUG_SLEEP_STOP=y

# Cortex
CONFIG_FPU=y

# Memory
CONFIG_FLASH=y
CONFIG_STM32_MEMMAP=y
CONFIG_MEMC=y

# XIP
CONFIG_CODE_DATA_RELOCATION=y
CONFIG_HAVE_CUSTOM_LINKER_SCRIPT=y
CONFIG_CUSTOM_LINKER_SCRIPT="xip.ld"
CONFIG_COVERAGE=n
CONFIG_XIP=y

# C/C++
CONFIG_STD_C23=y
CONFIG_GNU_C_EXTENSIONS=y
CONFIG_CPP=y
CONFIG_CPP_RTTI=y
CONFIG_STD_CPP23=y
CONFIG_REQUIRES_FLOAT_PRINTF=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_LOG_MODE_IMMEDIATE=y
# CONFIG_LOG_MODE_DEFERRED is not set
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_UART_AUTOSTART=y
CONFIG_LOG_BACKEND_SWO=y
CONFIG_LOG_BACKEND_SWO_FREQ_HZ=50000000

# Bindesc
CONFIG_BINDESC=y
CONFIG_BINDESC_DEFINE=y

# Pripherals
CONFIG_SDHC=y
CONFIG_RTC=y
CONFIG_RTC_ALARM=y
CONFIG_RTC_CALIBRATION=y
CONFIG_GPIO=y
